[tool.bumpversion]
    commit           = true
    current_version  = "1.0.0"
    message          = "Bump version: {current_version} → {new_version}"
    parse            = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
    pre_commit_hooks = ["node scripts/update-changelog.mjs"]
    serialize        = ["{major}.{minor}.{patch}"]
    tag              = true
    tag_name         = "v{new_version}"

    [[tool.bumpversion.files]]
        filename = "package.json"
        replace  = '"version": "{new_version}"'
        search   = '"version": "{current_version}"'
