[[repos]]
  hooks = [{ id = "oxfmt" }]
  repo = "https://github.com/oxc-project/mirrors-oxfmt"
  rev = "v0.42.0"

[[repos]]
  hooks = [{ id = "oxlint" }]
  repo = "https://github.com/oxc-project/mirrors-oxlint"
  rev = "v1.57.0"
